name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.408
        
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
        
    - name: Restore NuGet packages
      run: nuget restore
      
    - name: Build
      run: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\devenv" "D:\a\Rock\Rock\Rock.sln" /build Release'
      shell: cmd
      
    - name: Package
      run: dotnet nuget add source --username ethan-sparkdevnetwork --password ${{ secrets.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  }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/ethan-sparkdevnetwork/index.json"
